### ISSUE TITLE
Ensure SB2 process path

### ISSUE THREAD

**Issue by fenwickjb** [MacdonEm/SCATT-Improvements#10]
Make sure the previous (SB2) SCATT remains functional.

- [x] Find or create an SB2 file
- [x] Build SCATT executable
- [x] Run SCATT with SB2 input
- [x] Verify SCATT output

**Comment by MacdonEm** [comment]
From what I can tell, the txt file that went with my Scratch project is accurate. I forgot to delete a blank background so the numbers get inflated by 1 in a couple of areas, but technically it IS an element in the project so it IS being counted.

**Comment by MacdonEm** [comment]
I tested SCATT with a Scratch provided "beginner project" template as well as one I made from... scratch... Okay, I get the name now. Anyway, the home-brewed Scratch project is what's still in the submissions/analyzedReports directories.
