### ISSUE TITLE
Update SCATT: sb2/sb3 version discrimination

### ISSUE THREAD

**Issue by MacdonEm** [MacdonEm/SCATT-Improvements#2]
After verifying SCATT operates properly with normal .sb2 files (may need to change directory path again), add method to verify Scratch version (either 2 or 3) and use the proper "track" for that version.

At this point, the only track available should be the version 2 track. So, really the method should correctly discern version 2 versus version 3, operate as normal for version 2, and do nothing for version 3.

**Comment by fenwickjb** [comment]
I'd rename this issue as: **SB2 or SB3 version discrimination**.
Take input SB* file and figure out which version it is. (Look inside, don't rely on file extension.)
Then route SB2 files to normal "process Scratch SB2 file" path. Route SB3 files to a new process path that (for now) says something like "SB3 process under construction."

**Comment by fenwickjb** [comment]
This should be worked on come AFTER #10.
